
-- MySQL Script generated by MySQL Workbench
-- 03/02/16 18:11:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_pnv_forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pnv_forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pnv_forum` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_pnv_forum` ;

-- -----------------------------------------------------
-- Table `db_pnv_forum`.`tai_khoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`tai_khoan` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`tai_khoan` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_name` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `quyen` INT NOT NULL COMMENT '',
  `is_active` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnv_forum`.`thong_tin_ca_nhan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`thong_tin_ca_nhan` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`thong_tin_ca_nhan` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ten` VARCHAR(45) NOT NULL COMMENT '',
  `tuoi` INT NULL COMMENT '',
  `lop` VARCHAR(45) NOT NULL COMMENT '',
  `dia_chi` VARCHAR(80) NULL COMMENT '',
  `email` VARCHAR(60) NULL COMMENT '',
  `avatar` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `account_profile_id_pk`
    FOREIGN KEY (`id`)
    REFERENCES `db_pnv_forum`.`tai_khoan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnv_forum`.`chu_de`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`chu_de` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`chu_de` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `chu_de` VARCHAR(55) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnv_forum`.`bai_dang_hoac_trao_doi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`bai_dang_hoac_trao_doi` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`bai_dang_hoac_trao_doi` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_chu_de` INT NULL COMMENT '',
  `tieu_de` VARCHAR(255) NULL COMMENT '',
  `the_loai_bai` TINYINT(1) NULL COMMENT '',
  `noi_dung` VARCHAR(20000) NULL COMMENT '',
  `luot_thich` INT NULL COMMENT '',
  `ngay_dang_bai` DATETIME NULL COMMENT '',
  `spam` INT NULL COMMENT '',
  `is_active` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `chu_de_bai_dang_hoac_trao_doi_id_chu_de_pk_idx` (`id_chu_de` ASC)  COMMENT '',
  CONSTRAINT `chu_de_bai_dang_hoac_trao_doi_id_chu_de_pk`
    FOREIGN KEY (`id_chu_de`)
    REFERENCES `db_pnv_forum`.`chu_de` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnv_forum`.`binh_luan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`binh_luan` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`binh_luan` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_reference` INT NULL COMMENT '',
  `id_thong_tin_ca_nhan` INT NOT NULL COMMENT '',
  `id_bai_dang_hoac_trao_doi` INT NOT NULL COMMENT '',
  `noi_dung` VARCHAR(1000) NOT NULL COMMENT '',
  `ten_nguoi_binh_luan` VARCHAR(45) NOT NULL COMMENT '',
  `binh_luan_con` TINYINT(1) NULL COMMENT '',
  `ngay` DATETIME NULL COMMENT '',
  `spam` INT NULL COMMENT '',
  `is_active` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `bai_dang_hoac_trao_doi_binh_luan_id_bai_dang_hoac_trao_doi__idx` (`id_bai_dang_hoac_trao_doi` ASC)  COMMENT '',
  INDEX `binh_luan_binh_luan_id_reference_pk_idx` (`id_reference` ASC)  COMMENT '',
  INDEX `thong_tin_ca_nhan_binh_luan_id_thong_tin_ca_nhan_pk_idx` (`id_thong_tin_ca_nhan` ASC)  COMMENT '',
  CONSTRAINT `bai_dang_hoac_trao_doi_binh_luan_id_bai_dang_hoac_trao_doi_pk`
    FOREIGN KEY (`id_bai_dang_hoac_trao_doi`)
    REFERENCES `db_pnv_forum`.`bai_dang_hoac_trao_doi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `binh_luan_binh_luan_id_reference_pk`
    FOREIGN KEY (`id_reference`)
    REFERENCES `db_pnv_forum`.`binh_luan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `thong_tin_ca_nhan_binh_luan_id_thong_tin_ca_nhan_pk`
    FOREIGN KEY (`id_thong_tin_ca_nhan`)
    REFERENCES `db_pnv_forum`.`thong_tin_ca_nhan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnv_forum`.`loai_tep_tin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`loai_tep_tin` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`loai_tep_tin` (
  `id` INT NOT NULL COMMENT '',
  `ten_loai_tep` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnv_forum`.`dinh_kem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pnv_forum`.`dinh_kem` ;

CREATE TABLE IF NOT EXISTS `db_pnv_forum`.`dinh_kem` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_bai_dang_hoac_trao_doi` INT NULL COMMENT '',
  `id_loai_tep_tin` INT NULL COMMENT '',
  `tep_tin` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `bai_dang_hoac_trao_doi_dinh_kem_id_bai_dang_hoac_trao_doi_p_idx` (`id_bai_dang_hoac_trao_doi` ASC)  COMMENT '',
  INDEX `loai_tep_tin_dinh_kem_id_loai_tep_tin_pk_idx` (`id_loai_tep_tin` ASC)  COMMENT '',
  CONSTRAINT `bai_dang_hoac_trao_doi_dinh_kem_id_bai_dang_hoac_trao_doi_pk`
    FOREIGN KEY (`id_bai_dang_hoac_trao_doi`)
    REFERENCES `db_pnv_forum`.`bai_dang_hoac_trao_doi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `loai_tep_tin_dinh_kem_id_loai_tep_tin_pk`
    FOREIGN KEY (`id_loai_tep_tin`)
    REFERENCES `db_pnv_forum`.`loai_tep_tin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;